name: Build & Test on Self-Hosted Runners

on:
  push:
    branches: [2.1-branch]
  pull_request:
    branches: [2.1-branch]

jobs:
  build-test-windows:
    name: Build & Test on Windows
    runs-on: [self-hosted, windowsRunner]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create test result (Windows)
        run: |
          echo "Selenium login test passed on Windows Runner." > test_result_windows.txt

      - name: Upload test result (Windows)
        uses: actions/upload-artifact@v4
        with:
          name: test-report-windows
          path: test_result_windows.txt

  build-test-linux:
    name: Build & Test on Linux
    runs-on: [self-hosted, linuxRunner]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create test result (Linux)
        run: echo "Selenium login test passed on Linux Runner." > test_result_linux.txt

      - name: Upload test result (Linux)
        uses: actions/upload-artifact@v4
        with:
          name: test-report-linux
          path: test_result_linux.txt
