name: Build & Test on Self-Hosted Runners

on:
  push:
    branches: [2.1-branch]
  pull_request:
    branches: [2.1-branch]

jobs:
  build-test-windows:
    name: Build & Simulate Test on Windows
    runs-on: [self-hosted, windows]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create fake test result (Windows)
        run: |
          echo "Selenium login test passed on Windows Runner." > test_result_windows.txt

      - name: Upload simulated test result (Windows)
        uses: actions/upload-artifact@v4
        with:
          name: simulated-test-report-windows
          path: test_result_windows.txt

  build-test-linux:
    name: Build & Simulate Test on Linux
    runs-on: [self-hosted, linux]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create fake test result (Linux)
        run: echo "Selenium login test passed on Linux Runner." > test_result_linux.txt

      - name: Upload simulated test result (Linux)
        uses: actions/upload-artifact@v4
        with:
          name: simulated-test-report-linux
          path: test_result_linux.txt
